### PR TITLE
Create cems-learnings-documentation

### PR DESCRIPTION
**Pull request by cemyilmaz1**

### CODE REVIEW

**Comment by cemyilmaz1** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0CAcQjRxqFQoTCKXfifm4zMgCFQI7Pgod_RUL0w&url=http%3A%2F%2Fwww.romalearningleaders.eu%2Fdocumentation%2F&psig=AFQjCNGxgXgQO_qhDNblO_10ZoLqZK5OjQ&ust=1445272280423694

**Comment by cemyilmaz1** [comment]
documentation

**Comment by vvirgintino** [comment]
I love orange folders!

**Comment by vvirgintino** [comment]
Check out this article about team dynamics: http://www.nytimes.com/2015/10/19/sports/baseball/matt-harvey-new-york-mets-chicago-cubs-nlcs.html?hp&action=click&pgtype=Homepage&module=second-column-region&region=top-news&WT.nav=top-news&_r=0

**Comment by cemyilmaz1** [comment]
@danajsilb @JaimieH @sreyab @vvirgintino If you ever need to learn more about documentation, make sure to check this manual out! : https://git-scm.com/documentation

**Comment by sreyab** [comment]
@cemyilmaz1 :+1: ready to ship

**Comment by JaimieH** [comment]
Love the color combo! So fetch.

**Comment by danajsilb** [comment]
@JaimieH really on point :+1:

**Pull request merged**
