### PR TITLE
Create sreyas-takeaway.md

### PR DESCRIPTION
**Pull request by sreyab**

### CODE REVIEW

**Comment by vvirgintino** [comment]
Keep up the good work

**Comment by sreyab** [comment]
image

**Comment by vvirgintino** [comment]
A word of caution from a case study on the firefighter's union: http://www.nytimes.com/2015/10/18/business/firefighters-union-owes-clout-to-its-free-spending-chief.html?hpw&rref=business&action=click&pgtype=Homepage&module=well-region&region=bottom-well&WT.nav=bottom-well

**Comment by cemyilmaz1** [comment]
@sreyab @JaimieH @vvirgintino @danajsilb 13 cases where software development failed: http://successfulsoftware.net/2010/05/27/learning-lessons-from-13-failed-software-products/
Interesting.. Especially how each case defines time/money/effort loss in different ways. Hard to quantify time lost.

**Comment by cemyilmaz1** [comment]
Looking good S :+1:

**Comment by JaimieH** [comment]
Sreya you really need to teach me about life. You are so wise.

**Comment by danajsilb** [comment]
@sreyab love the sassy green guy! :+1:

**Comment by sreyab** [comment]
another helpful link - http://thenextweb.com/entrepreneur/2012/11/04/the-non-developers-guide-to-hiring-software-developers/

**Pull request merged**
