### PR TITLE
danas-takeaways-communication

### PR DESCRIPTION
**Pull request by danajsilb**

### CODE REVIEW

**Comment by sreyab** [comment]
looks good. maybe add an image @danajsilb

**Comment by danajsilb** [comment]
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=0CAcQjRxqFQoTCJat7o_rvcgCFUhsHgod7JIHhg&url=http%3A%2F%2Fwww.abbymedcalf.com%2Ftop-tips-for-effective-communication%2F&bvm=bv.104819420,d.dmo&psig=AFQjCNFILMev_ZOJtBEPvxFM_lF4wN-7PQ&ust=1444770259200469

**Comment by danajsilb** [comment]
dp-communication-heads

**Comment by vvirgintino** [comment]
Great work Dana!

**Comment by cemyilmaz1** [comment]
@danajsilb Duhigg talks about changing habits to change the way we communicate (keystone habits) in his book the Power of Habit: http://www.huffingtonpost.com/charles-duhigg/the-power-of-habit_b_1304550.html
Great book, a must-read!

**Comment by cemyilmaz1** [comment]
Looks good :+1:

**Comment by danajsilb** [comment]
@cemyilmaz1 @sreyab @JaimieH @vvirgintino here's a really interesting article from Huff Post with tips for effective communication for remote teams, which is particularly relevant for us http://www.huffingtonpost.com/syed-balkhi/effective-communication-t_1_b_3672210.html

**Comment by sreyab** [comment]
going beyond software communication but also relevant when communicating with people across the globe - http://www.boston.com/business/blogs/global-business-hub/2012/04/five_tips_for_c.html

**Pull request merged**
