### PR TITLE
Create 100percenthiggins

### PR DESCRIPTION
**Pull request by JaimieH**
…when both developing and specifying software. Given the trend towards agile software development and an emphasis on working documents over final products, it is necessary that Programmers are willing to change and adjust accordingly as the project priorities shift and as everyone continues to learn from prior versions. Given the fact that initial assumptions will inevitably morph and change over the course of the project, one should seek programmers who understand the importance of flexibility.

### CODE REVIEW

**Comment by JaimieH** [comment]
Practical 
untitled

**Comment by JaimieH** [comment]
Here is a relevant article on 'agile' software development:
http://www.allaboutagile.com/10-good-reasons-to-do-agile-development/
-- Jaimie Higgins

**Comment by vvirgintino** [comment]
Hi Jaimie thanks for doing this! Love the picture.

**Comment by sreyab** [comment]
@JaimieH looks awesome Jaimie. Love the article - really useful!

**Comment by cemyilmaz1** [comment]
@JaimieH This is so typical of you :) :+1: from me!

**Comment by danajsilb** [comment]
@JaimieH this is great! :+1: We need to redefine business casual for yoga typing

**Pull request merged**
